Vagrant.configure("2") do |config|
  config.vm.define "mongo1" do |mongo1|
    mongo1.vm.box     = "precise64"
    mongo1.vm.box_url = "http://files.vagrantup.com/precise64.box"
    mongo1.vm.hostname = "mongo1"

    # mongo1.vm.network "33.33.33.10"
    mongo1.vm.network "private_network", type: "dhcp"
    mongo1.vm.network "forwarded_port", guest: 27017, host: 27018

    mongo1.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "base.pp"
      puppet.module_path    = "modules"
    end

  end

  config.vm.define "mongo2" do |mongo2|
    mongo2.vm.box     = "precise64"
    mongo2.vm.box_url = "http://files.vagrantup.com/precise64.box"
    mongo2.vm.hostname = "mongo2"
    # mongo2.vm.network "33.33.33.10"
    mongo2.vm.network "private_network", type: "dhcp"
    mongo2.vm.network "forwarded_port", guest: 27017, host: 27019

    mongo2.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "base.pp"
      puppet.module_path    = "modules"
    end
  end

  config.vm.define "mongo3" do |mongo3|
    mongo3.vm.box     = "precise64"
    mongo3.vm.box_url = "http://files.vagrantup.com/precise64.box"
    mongo3.vm.hostname = "mongo3"
    # mongo3.vm.network "33.33.33.10"
    mongo3.vm.network "private_network", type: "dhcp"
    mongo3.vm.network "forwarded_port", guest: 27017, host: 27020

    mongo3.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "base.pp"
      puppet.module_path    = "modules"
    end
  end
end
